title: 
#logo: /assets/img/xxx.png <path of img>
description: I'm a data-driven professional, a mentor with a keen interest in Data Science Analytics, NLP, ML and their applications in solving business problem
show_downloads: true
theme: jekyll-theme-minimal
#URL for themes: https://pages.github.com/themes/
